name: tariffs_repository
description: My tariffs repo
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tariff_api:
    path: ../tariff_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0