name: tariff_api
description: My tariff  package
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  meta: ^1.3.0
  uuid: ^3.0.4
  rxdart: ^0.27.2
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0